// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:injectable/injectable.dart';
import 'camera_list_params.dart';
import 'package:core/core.dart';

@LazySingleton(scope: 'cameraList')
class CameraListViewModel extends BaseViewModel {
  final params = CameraListParams();

  @override
  void onInit() {
    // called immediately after the widget is allocated in memory.
    super.onInit();
  }

  @override
  void onDispose() {
    // called immediately before the widget is disposed
    super.onDispose();
  }
}
