// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'camera_injectable.config.dart';

/// manage dependencies
@InjectableInit()
Future<void> configureCameraDependencies({Environment? environment}) async {
  GetIt.instance.init(environment: environment?.name);
}
