// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:authentication/src/common/ui/widgets/text_fields/verify_pin_code_widget.dart';
import 'package:flutter/material.dart';
import '../viewmodels/verify_pin_code_viewmodel.dart';
import 'package:core/core.dart';

class VerifyPinCodeMobileScreen extends StatelessWidget {
  const VerifyPinCodeMobileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<VerifyPinCodeViewModel>(
      builder: (VerifyPinCodeViewModel viewModel) {
        return BaseScrollView(
          padding: adaptivePadding,
          child: VerifyPinCodeWidget(
            code: viewModel.params.code,
            receiver: viewModel.params.phone,
            onChanged: viewModel.onPinCodeChanged,
            onSubmit: viewModel.submitVerificationCode,
            onResendCode: viewModel.requestVerificationCode,
          ),
        );
      },
    );
  }
}
