// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import 'package:injectable/injectable.dart';
import 'package:core/core.dart';
part 'authentication_remote_data_source.g.dart';

@LazySingleton(scope: 'authentication')
@RestApi()
abstract class AuthenticationRemoteDataSource {
  @factoryMethod
  factory AuthenticationRemoteDataSource(Dio dio) =
      _AuthenticationRemoteDataSource;

  @POST('/login')
  Future<BaseResponse<dynamic>> login({
    @Body() required Map<String, dynamic> data,
    @CancelRequest() CancelToken? cancelToken,
  });

  @POST('/auth/verify')
  Future<BaseResponse<dynamic>> verifyPinCode({
    @Body() required Map<String, dynamic> data,
    @CancelRequest() CancelToken? cancelToken,
  });

  @POST('/auth/resend-code')
  Future<BaseResponse<dynamic>> resendVerificationCode({
    @Body() required Map<String, dynamic> data,
    @CancelRequest() CancelToken? cancelToken,
  });
}
