name: authentication
version: 0.0.1
homepage: none
publish_to: none
description: Authentication Package
environment: 
  sdk: ^3.6.0
  flutter: '>=1.17.0'
dependencies:
  pinput: ^5.0.0
  easy_localization: ^3.0.1
  flutterx_live_data: ^1.9.6
  responsive_builder: ^0.7.0
  dio: ^5.1.2
  retrofit: ^4.0.1
  injectable: ^2.5.0
  get_it: ^8.0.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.1.0
  camera:
  core: 
  flutter: 
    sdk: flutter
  reactive_forms: any
  reactive_phone_form_field: any
  equatable: ^2.0.7
  auto_route: ^9.3.0+1
  green_villas:
dev_dependencies:
  auto_route_generator: ^9.0.0
  retrofit_generator: ^7.0.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.4.1
  build_runner: ^2.4.11
  freezed: ^2.5.7 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
