name: green_villas
description: "A new Flutter project."
version: 1.0.0+1
homepage: none
publish_to: none
environment:
  sdk: ^3.6.0
dependencies:
  authentication:
  camera:
    path: ../../packages/camera
  flutterx_live_data: ^1.9.6
  flutter_native_splash: ^2.4.1
  easy_localization: ^3.0.1
  core:
  injectable: ^2.5.0
  get_it: ^8.0.1
  auto_route: ^9.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/localization/
    - assets/images/
    - assets/svgs/
