// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:authentication/src/authentication/data/repositories/authentication/authentication_repository.dart';
import 'package:injectable/injectable.dart';
import 'login_params.dart';
import 'package:core/core.dart';

@LazySingleton(scope: 'login')
class LoginViewModel extends BaseViewModel {
  final params = LoginParams();
  final AuthenticationRepository _authenticationRepository;
  LoginViewModel(this._authenticationRepository);

  @override
  void onInit() {
    // called immediately after the widget is allocated in memory.
    super.onInit();
  }

  @override
  void onDispose() {
    // called immediately before the widget is disposed
    _authenticationRepository.dispose();
    super.onDispose();
  }

  void submit() {
    eventBus.fire(const SoftKeyboardEvent());
    params.setResult('success');
    //TODO: call API LOGIN
    // final request = LoginRequest(
    //   phone:
    //       params.loginForm.getControlValue<PhoneNumber>('phone')?.international,
    // );
    // callHttpRequest(
    //   () => _authenticationRepository.login(request),
    //   setLoading: baseParams.setLoading,
    //   callback: (result, success) {
    //     if (result != null && success) {
    //       params.setResult(result!);
    //     }
    //   },
    // );
  }
}
