// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';

class DesignColors {
  static const Color primaryColor = Color(0xFF27338C);
  static const Color secondaryColor = Color(0xFFA6AB00);
  static const Color scaffoldBackgroundColor = Color(0xFFFFFFFF);
  static const Color textColor = Color(0xFF202020);
  static const Color grey = Color(0xFFAFB0B6);
}
