// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'dart:async';
import 'package:core/core.dart';
import 'package:authentication/src/authentication/data/models/requests/login_request/login_request.dart';
import 'package:authentication/src/authentication/data/models/requests/verify_code_request/verify_code_request.dart';
import 'package:authentication/src/authentication/data/models/requests/get_verification_code_request/get_verification_code_request.dart';

abstract class AuthenticationRepository {
  Future<BaseResponse<dynamic>> login(LoginRequest data);

  Future<BaseResponse<dynamic>> verifyPinCode(VerifyCodeRequest data);

  Future<BaseResponse<dynamic>> resendVerificationCode(
      GetVerificationCodeRequest data);

  void dispose();
}
