// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import '../common/router/app_router.dart';
import './viewmodels/home_viewmodel.dart';
import 'package:auto_route/auto_route.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:core/core.dart';
import '../common/di/app_injectable.config.dart';

@RoutePage(name: 'home')
class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen>
    with LifecycleOwner<HomeScreen, HomeViewModel>, ObserverMixin {
  bool isRed = false;
  @override
  void initState() {
    // TODO: implement initState
    print('111111 init State');
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: BaseAppBar(title: 'home'.tr()),
      body: SafeArea(
        child: Container(
          height: 200,
          width: 200,
          color: isRed ? Colors.red[500] : Colors.amber[100],
          child: GestureDetector(
            onTap: () {
              print('11111 HomeScreen onTap');
              appRouter.pushNamed('/camera_list');
            },
            child: Center(
              child: Text('Home Screen'),
            ),
          ),
        ),
      ),
    );
  }

  @override
  DiScope get diScope => DiScope(
        name: 'home',
        factory: getIt.initHomeScope,
        dependencies: [],
      );
}
