name: camera
version: 0.0.1
homepage: none
publish_to: none
description: Camera Package
environment: 
  sdk: ^3.6.0
  flutter: '>=1.17.0'
dependencies:
  flutterx_live_data: ^1.9.6
  auto_route: ^9.2.2
  injectable: ^2.5.0
  get_it: ^8.0.1
  core: 
  flutter: 
    sdk: flutter
dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
