name: camera
version: 0.0.1
homepage: none
publish_to: none
description: Camera Package
environment: 
  sdk: ^3.6.0
  flutter: '>=1.17.0'
dependencies:
  core: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
